### ISSUE TITLE
No CSS?!?!?

### ISSUE THREAD

**Issue by cs3vigny** [Jacobs63/vue3-tabs-component#47] opened 2023-10-26 14:31 UTC
Why would you not include a default CSS to import? Something like this:

import "bootstrap/dist/css/bootstrap.min.css";

Just add it into the report with the most basic styling so that it doesn't load list bullets, etc.

**Comment by Jacobs63** [comment] 2023-10-26 14:35
Duplicate of https://github.com/Jacobs63/vue3-tabs-component/issues/32

**Closed as completed by Jacobs63** 2023-10-26 14:35 UTC
