### ISSUE TITLE
Add CSS to package

### ISSUE THREAD

**Issue by LoicGombeaud** [Jacobs63/vue3-tabs-component#33] opened 2023-02-18 15:08 UTC
Hi, thanks for this component!

Would you perharps consider adding some CSS to the published package, for example [the one you use in the demo](https://github.com/Jacobs63/vue3-tabs-component/blob/master/docs/resources/tabs-component.css)?

It would make the import much faster and give a good base to start from.

**Comment by Jacobs63** [comment] 2023-02-20 09:08
Hello,

duplicate of #32 

There is no intention of adding any css to the published package, you're free to copy it from the repo if that would help.

**Closed as completed by Jacobs63** 2023-02-20 09:08 UTC

**Comment by LoicGombeaud** [comment] 2023-02-20 09:10
Sorry about that, I forgot to check the existing issues beforehand. Thanks again for this great component.
