### ISSUE TITLE
valid ES Module

### ISSUE THREAD

**Issue by lperez22** [Jacobs63/vue3-tabs-component#11] opened 2022-02-11 20:35 UTC
Hello we are currently using this package with Nuxt3 and now all packages are required to be valid ES Modules, this package does work in our project however we get the following warning and wanted to know if this package could be corrected

`vue3-tabs-component doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.`

**Comment by Jacobs63** [comment] 2022-07-05 13:23
Greetings,

`unpkg` & `module` were defined in 1.0.11, which should help with this issue.

However, I was unable to reproduce this on a fresh Nuxt3 installation beforehand either, so if you could add some steps to reproduce I'd appreciate it.

**Comment by lperez22** [comment] 2022-07-06 12:28
At the time we were on version 1.0.5, running nuxi build produced this message 
![image](https://user-images.githubusercontent.com/91892011/177549976-80342a19-0fa3-48ee-8158-ed0fbe780a81.png)
but with the latest version of this package I no longer get the warning so no longer an issue.

**Comment by Jacobs63** [comment] 2022-07-06 12:30
Thank you for the clarification, so it should be fixed now.

**Closed as completed by Jacobs63** 2022-07-06 12:30 UTC
